name: Auto Download and Commit

on: 
  push:
    branches:
      [master]

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
      - name: Download file
        run: |
          touch downloaded_file 
      
      - name: Commit with URL as message
        run: |
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b downl origin/downl
          git add downloaded_file
          git commit -m "mmmnmmn"
          git push origin downl
          
